config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reservation.urls", namespace="main")),
    path("users/", include("users.urls", namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

reservation/urls.py
from django.urls import path

from reservation.apps import ReservationConfig
from reservation.views import (
    AboutView,
    Contacts,
    Feedback,
    MainView,
    Mission,
    PersonalAccountListView,
    ReservationCreateView,
    ReservationDeleteView,
    ReservationListView,
    ReservationUpdateView,
    Services,
    Team,
    History,
)

app_name = ReservationConfig.name

urlpatterns = [
    # path('', home, name='home'),
    path("", MainView.as_view(), name="main"),
    path("contacts/", Contacts.as_view(), name="contacts"),
    path("feedback/", Feedback.as_view(), name="feedback"),
    path("about/", AboutView.as_view(), name="about"),
    path("services/", Services.as_view(), name="services"),
    path("mission/", Mission.as_view(), name="mission"),
    path("history/", History.as_view(), name="history"),
    path("team/", Team.as_view(), name="team"),
    path("reservation/", ReservationListView.as_view(), name="reservation_list"),
    path(
        "reservation/create/",
        ReservationCreateView.as_view(),
        name="reservation_create",
    ),
    path(
        "reservation/<int:pk>/update/",
        ReservationUpdateView.as_view(),
        name="reservation_update",
    ),
    path(
        "reservation/<int:pk>/delete/",
        ReservationDeleteView.as_view(),
        name="reservation_delete",
    ),
    path("personal_account/", PersonalAccountListView.as_view(), name="personal_account"),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserCreateView, UserForgotPasswordView, UserPasswordResetConfirmView, email_verification

app_name = UsersConfig.name

urlpatterns = [
    path("login/", LoginView.as_view(template_name="login.html"), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("register/", UserCreateView.as_view(), name="register"),
    path("email-confirm/<str:token>/", email_verification, name="email-confirm"),
    path("password-reset/", UserForgotPasswordView.as_view(), name="password_reset"),
    path(
        "set-new-password/<uidb64>/<token>/",
        UserPasswordResetConfirmView.as_view(),
        name="password_reset_confirm",
    ),
]

reservation/models.py
from django.db import models

from users.models import User

NULLABLE = {"blank": True, "null": True}


class Restaurant(models.Model):
    """Модель ресторана."""

    name = models.CharField(max_length=20, verbose_name="Название", help_text="Введите название")
    description = models.TextField(verbose_name="Описание", help_text="Введите описание")
    history = models.TextField(
        verbose_name="История ресторана",
        help_text="Введите описание истории",
        **NULLABLE,
    )
    mission = models.TextField(
        verbose_name="Миссия и ценности",
        help_text="Введите описание миссии и ценностей",
        **NULLABLE,
    )
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        help_text="Укажите владельца",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Ресторан"
        verbose_name_plural = "Рестораны"
        ordering = [
            "name",
        ]


class Table(models.Model):
    """Модель стола."""

    number = models.IntegerField(unique=True, verbose_name="Номер стола")
    capacity = models.IntegerField(verbose_name="Вместимость столика")
    is_available = models.BooleanField(default=True, verbose_name="Доступность столика")
    owner = models.ForeignKey(
        User,
        verbose_name="Владелец",
        help_text="Укажите владельца",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"№ {self.number} (Вместимость: {self.capacity})"


class Reservation(models.Model):
    """Модель бронирования."""

    table = models.ForeignKey(Table, on_delete=models.CASCADE, verbose_name="Номер столика")
    reserved_at = models.DateTimeField(verbose_name="Дата бронирования")
    customer_name = models.CharField(max_length=100, verbose_name="Имя клиента")
    customer_contact = models.CharField(max_length=100, verbose_name="Контактная информация")
    owner = models.ForeignKey(
        User,
        verbose_name="Пользователь",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    def __str__(self):
        return f"Зарезервировано для {self.customer_name} в {self.reserved_at} столик {self.table}"

    class Meta:
        verbose_name = "Бронирование"
        verbose_name_plural = "Бронирования"
        ordering = [
            "reserved_at",
        ]

reservation/forms.py
from django import forms
from django.forms import ModelForm

from reservation.models import Reservation, Restaurant


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"


class RestaurantForm(StyleFormMixin, ModelForm):
    """Форма создания нового ресторана."""

    class Meta:
        model = Restaurant
        fields = "__all__"


class ReservationForm(ModelForm):
    """Форма бронирования столика."""

    class Meta:
        """Стилизация формы бронирования столика."""

        model = Reservation
        fields = ["owner", "table", "reserved_at", "customer_name", "customer_contact"]
        widgets = {
            'owner': forms.HiddenInput(),
            "reserved_at": forms.DateTimeInput(
                attrs={
                    "class": "form-control",
                    "placeholder": "Выберите дату и время",
                    "type": "datetime-local",  # для выбора даты и времени
                }
            ),
        }

    def __init__(self, *args, **kwargs):
        super(ReservationForm, self).__init__(*args, **kwargs)
        self.fields["table"].widget.attrs.update({"class": "form-control"})
        self.fields["customer_name"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Уточните имя на кого бронируете столик",
            }
        )
        self.fields["customer_contact"].widget.attrs.update(
            {
                "class": "form-control",
                "placeholder": "Укажите контактный номер телефона для связи",
            }
        )
        self.fields["owner"].widget.attrs.update({"class": "form-control"})

    # Настройки для формы, если использовать форму отдельно
    # def clean(self):
    #     """Валидация формы, на проверку отсутствия брони выбранного столика."""
    #     cleaned_data = super().clean()
    #     table = cleaned_data.get("table")
    #     reserved_at = cleaned_data.get("reserved_at")
    #
    #     if reserved_at and reserved_at < timezone.now():
    #         raise ValidationError("Выбранное время и дата не могут быть в прошлом.")
    #
    #     if table and reserved_at:
    #         # Определяем начальное и конечное время бронирования
    #         start_time = reserved_at
    #         end_time = reserved_at + timedelta(minutes=60)
    #
    #         # Проверяем, есть ли текущее бронирование на этот столик
    #         if Reservation.objects.filter(
    #                 Q(table=table) &
    #                 Q(reserved_at__lt=end_time) &
    #                 Q(reserved_at__gte=start_time)
    #         ).exists() or Reservation.objects.filter(
    #             Q(table=table) &
    #             Q(reserved_at__gte=start_time) &
    #             Q(reserved_at__lt=end_time)
    #         ).exists():
    #             raise ValidationError(f"Выбранный стол №{table.number} уже забронирован на это время, пожалуйста выберите другое время.")
    #
    #     return cleaned_data
    #
    # def save(self, commit=True):
    #     """Сохранение успешного бронирования."""
    #     reservation = super().save(commit=False)
    #
    #     if commit:
    #         reservation.save()  # Сохраняем в БД
    #     return reservation

reservation/views.py
from datetime import timedelta

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.generic import CreateView, DeleteView, ListView, TemplateView, UpdateView
from rest_framework.permissions import IsAuthenticatedOrReadOnly, IsAdminUser, IsAuthenticated

from reservation.forms import ReservationForm
from reservation.models import Reservation, Restaurant


def home(request):
    """Основной шаблон."""
    return render(request, "home.html")


class Contacts(TemplateView):
    """Cтраница контакты."""

    template_name = "reservation/contacts.html"

    def post(self, request, *args, **kwargs):
        """Обработка POST-запроса ответа на обратную связь."""
        if request.method == "POST":
            name = request.POST.get("name")  # получаем имя
            # message = request.POST.get("message")  # получаем сообщение
            # Отправляем сообщение об успешной отправке
            messages.success(request, f"Спасибо, {name}! Ваше сообщение успешно отправлено.")
            return redirect("reservation:contacts")  # Перенаправляем на ту же страницу
        return render(request, self.template_name)


class Feedback(TemplateView):
    """Cтраница обратной связи."""

    template_name = "reservation/feedback.html"


class MainView(TemplateView):
    """Главная страница."""

    model = Restaurant
    template_name = "reservation/main.html"


class AboutView(TemplateView):
    """Страница о ресторане."""

    model = Restaurant
    template_name = "reservation/about.html"


class ReservationListView(LoginRequiredMixin,ListView):
    """Страница бронирования."""

    model = Reservation
    template_name = "reservation/reservation_list.html"
    context_object_name = "reservation"
    success_url = reverse_lazy("reservation:reservation_list")
    form_class = ReservationForm


    def get_object(self, queryset=None):
        """Получение одного объекта."""
        self.object = super().get_object(queryset)
        self.object.save()
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionRequiredMixin

    def get_context_data(self, **kwargs):
        """Добавление данных в контекст шаблона."""
        context = super().get_context_data(**kwargs)
        context["form"] = ReservationForm()
        return context

    def post(self, request, *args, **kwargs):
        """Обработка POST-запроса."""
        form = self.form_class(request.POST)

        if form.is_valid():
            reservation = form.save(commit=False)
            reservation.owner = request.user
            reservation.save()

            # Проверка, находится ли время бронирования в прошлом
            if reservation.reserved_at and reservation.reserved_at < timezone.now():
                messages.error(
                    request,
                    "Дата бронирования не может быть в прошлом. Пожалуйста, выберите другое время.",
                )
                return self.get(request, *args, **kwargs)  # Возврат на ту же страницу

            # Проверка интервала бронирования (60 минут после)
            reserved_at = reservation.reserved_at
            start_time = reserved_at - timedelta(minutes=60)
            end_time = reserved_at


            # Проверка, есть ли уже бронирования в этом интервале
            interval_reservation = Reservation.objects.filter(reserved_at__range=(start_time, end_time)).exclude(
                id=reservation.id
            )  # Исключаем текущее бронирование, если оно уже существует

            if interval_reservation.exists():
                messages.error(
                    request,
                    "К сожалению, на это время уже занято. Выберите другой стол или дату.",
                )
                return self.get(request, *args, **kwargs)  # Возврат на ту же страницу

            # Если все проверки пройдены, сохраняем бронирование
            reservation.save()
            messages.success(request, "Ваше бронирование успешно зарегистрировано!")
            return redirect(self.success_url)  # Перенаправление на страницу с успешным бронированием

        # Если форма не прошла валидацию, отправляем общее сообщение об ошибке
        messages.error(
            request,
            "К сожалению, на это время уже занято. Выберите другой стол или дату",
        )
        return self.get(request, *args, **kwargs)  # Возврат на ту же страницу

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.groups.filter(name='admin').exists():
            return qs
        return qs.filter(owner=self.request.user)

class ReservationCreateView(LoginRequiredMixin, CreateView):
    """Страница создания бронирования."""

    model = Reservation
    form_class = ReservationForm
    template_name = "reservation/reservation_list.html"
    success_url = reverse_lazy("reservation:reservation_list")


    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)



class ReservationUpdateView(UpdateView, ):
    """Страница редактирование бронирования."""

    model = Reservation
    form_class = ReservationForm
    template_name = "reservation/reservation_list.html"
    context_object_name = "reservation"
    success_url = reverse_lazy("reservation:personal_account")


    def get_object(self, queryset=None):
        """Получение одного объекта."""
        reservation = super().get_object(queryset)
        if self.request.user != reservation.owner:
            raise PermissionRequiredMixin("Вы не можете редактировать это бронирование.")
        return reservation

    def get_context_data(self, **kwargs):
        """Добавление данных в контекст шаблона."""
        context = super().get_context_data(**kwargs)
        context["from_personal_account"] = True  # чтобы было доступно только при режиме редактирования
        return context

    def form_valid(self, form):
        """Обработка данных, если форма прошла валидацию."""
        reservation = form.save(commit=False)

        # Проверка, что дата бронирования не в прошлом
        if reservation.reserved_at and reservation.reserved_at < timezone.now():
            messages.error(self.request, "Дата бронирования не может быть в прошлом.")
            return self.form_invalid(form)

        # Проверка интервала бронирования (60 минут после)
        reserved_at = reservation.reserved_at
        start_time = reserved_at
        end_time = start_time + timedelta(minutes=60)

        # Проверка, есть ли уже бронирования в этом интервале
        interval_reservation = Reservation.objects.filter(reserved_at__range=(start_time, end_time)).exclude(
            id=reservation.id
        )  # Исключаем текущее бронирование

        if interval_reservation.exists():
            messages.error(self.request, "К сожалению, на это время уже занято.")
            return self.form_invalid(form)

        # Если все проверки пройдены, сохраняем бронирование
        reservation.save()
        messages.success(self.request, "Бронирование успешно обновлено!")
        return super().form_valid(form)


class ReservationDeleteView(DeleteView):
    """Cтраница удаления бронирования."""

    model = Reservation
    success_url = reverse_lazy("reservation:personal_account")


    def get_object(self, queryset=None):
        """Получение одного объекта."""
        self.object = super().get_object(queryset)
        if self.request.user == self.object.owner:
            self.object.save()
            return self.object
        raise PermissionRequiredMixin


class PersonalAccountListView(ListView):
    """Cтраница личного кабинета"""

    model = Reservation
    template_name = "reservation/personal_account.html"

    def get_queryset(self):
        """Набор данных, для отображения в представлении."""

        # Фильтруем по владельцу и сортируем по дате и столику
        queryset = Reservation.objects.filter(owner=self.request.user).order_by("reserved_at", "table")
        return queryset


class Services(TemplateView):
    """Cтраница услуги."""

    template_name = "reservation/services.html"


class Mission(TemplateView):
    """Cтраница миссия и ценности."""

    template_name = "reservation/mission.html"


class Team(TemplateView):
    """Cтраница команда."""

    template_name = "reservation/team.html"


class History(TemplateView):
    """Cтраница истории."""

    template_name = "reservation/history.html"

reservation/templates/reservation/includes/inc_footer.html
{% load static %}

  <footer class="mt-auto text-white-50" style="font-weight: normal; font-size: 0.75rem;">
    <p><strong>"НеРесторан" — это место, где правила классического ресторана теряют смысл. Уютная атмосфера,
        неожиданные вкусы, живое общение и свобода быть собой. Здесь нет официозности - только искренность, еда с характером и впечатления, которые останутся с вами навсегда...
        </strong></p>
  </footer>
</div>
<script src="{% static 'js/bootstrap.bundle.min.js.map' %}"></script>

    </body>
</html>

reservation/templates/reservation/includes/inc_header.html
{% load static %}

<html lang="en" class="h-100" data-bs-theme="auto">
  <head><script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>НеРесторан</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/cover/">

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Favicons -->
<link rel="apple-touch-icon" href="/media/1.jpg" sizes="180x180">
<link rel="icon" href="/media/1.jpg" sizes="32x32" type="image/png">
<link rel="icon" href="/media/1.jpg" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="{% static 'css/cover.css' %}" rel="stylesheet">
  </head>
  <!--  выравнивание основного текста-->
  <body class="d-flex h-100 text-center text-bg-dark">
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
      <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
      </symbol>
      <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
      </symbol>
      <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
      </symbol>
      <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
      </symbol>
    </svg>


<div class="cover-container d-flex w-100 h-100 p-1 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <!-- Центральная часть навигации -->
      <nav class="nav nav-masthead justify-content-center">
        {% if user.is_authenticated %}
        <a class="mt-auto text-white-50">{{ user.first_name }} {{ user.last_name }}, добро пожаловать в НеРесторан</a>
        {% endif %}
      </nav>
      <p></p>
      <!-- Левая часть навигации -->
      <nav class="nav nav-masthead justify-content-start float-start">
        <a class="btn btn-sm btn-outline-secondary mb-0" aria-current="page" href="{% url 'reservation:main' %}">Главная</a>
        <a class="btn btn-sm btn-outline-secondary mb-0" href="{% url 'reservation:about' %}">О ресторане</a>
        {% if user.is_authenticated %}
        <a class="btn btn-sm btn-outline-secondary mb-0" href="{% url 'reservation:reservation_list' %}">Бронирование</a>
        {% endif %}
      </nav>

      <!-- Правая часть навигации -->
      <nav class="nav nav-masthead justify-content-end float-end">
        {% if user.is_authenticated %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'reservation:personal_account' %}">Личный кабинет</a>
        {% endif %}

        {% if user.is_authenticated %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:logout' %}">Выход</a>
        {% else %}
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:login' %}">Вход</a>
        <a class="btn btn-sm btn-outline-secondary" href="{% url 'users:register' %}">Регистрация</a>
        {% endif %}
      </nav>

    </div>
  </header>